[package]
name = "webapp"
version = "0.1.0"
authors = ["chip reed <chip@chip.sh>"]

[dependencies]
includer = {path = "../../includer"}

[dev-dependencies]
select = "0.4"

[build-dependencies]
includer_codegen = { path = "../../includer_codegen" }
