[package]
name = "includer_codegen"
version = "0.1.0"
authors = ["chip reed <chip@chip.sh>"]

[features]
web = []

[dependencies]
includer = {path = "../includer"}
walkdir = "2"
quote = "0.6"
syn = "0.14"
regex = "1"
proc-macro2 = "0.4.14"
